# Import Libraries

In [2]:
import tensorflow as tf
import numpy as np
observations=1000
from tensorflow.keras.models import Sequential



# Generate data

In [19]:
xs=np.random.uniform(low=-10,high=10,size=(observations,1))
zs=np.random.uniform(low=-10,high=10,size=(observations,1))
generated_inp=np.column_stack((xs,zs))
noise=np.random.uniform(-1,1,(observations,1))
generated_op=2*xs-3*zs+5+noise
np.savez('Tf_intro',inputs=generated_inp,targets=generated_op)

# Train Data

In [20]:
training_data=np.load('Tf_intro.npz')
input_size=2
output_size=1
model=tf.keras.Sequential([ tf.keras.layers.Dense(output_size)   ])
                     
model.compile(optimizer='sgd',loss='mean_squared_error')
model.fit(training_data['inputs'],training_data['targets'],epochs= 100,verbose= 2)
    
    

Train on 1000 samples
Epoch 1/100
1000/1000 - 1s - loss: 45.3831
Epoch 2/100
1000/1000 - 0s - loss: 4.3490
Epoch 3/100
1000/1000 - 0s - loss: 1.4649
Epoch 4/100
1000/1000 - 0s - loss: 0.6681
Epoch 5/100
1000/1000 - 0s - loss: 0.4444
Epoch 6/100
1000/1000 - 0s - loss: 0.3982
Epoch 7/100
1000/1000 - 0s - loss: 0.3703
Epoch 8/100
1000/1000 - 0s - loss: 0.3661
Epoch 9/100
1000/1000 - 0s - loss: 0.3533
Epoch 10/100
1000/1000 - 0s - loss: 0.3633
Epoch 11/100
1000/1000 - 0s - loss: 0.3652
Epoch 12/100
1000/1000 - 0s - loss: 0.3668
Epoch 13/100
1000/1000 - 0s - loss: 0.3681
Epoch 14/100
1000/1000 - 0s - loss: 0.3612
Epoch 15/100
1000/1000 - 0s - loss: 0.3688
Epoch 16/100
1000/1000 - 0s - loss: 0.3674
Epoch 17/100
1000/1000 - 0s - loss: 0.3591
Epoch 18/100
1000/1000 - 0s - loss: 0.3632
Epoch 19/100
1000/1000 - 0s - loss: 0.3627
Epoch 20/100
1000/1000 - 0s - loss: 0.3618
Epoch 21/100
1000/1000 - 0s - loss: 0.3655
Epoch 22/100
1000/1000 - 0s - loss: 0.3648
Epoch 23/100
1000/1000 - 0s - loss: 0.36

# Extract Weights and Bias

In [21]:
weights=model.layers[0].get_weights()[0]
weights

array([[ 2.019899 ],
       [-3.0123985]], dtype=float32)

In [22]:
bias=model.layers[0].get_weights()[1]
bias

array([5.00074], dtype=float32)

Hence, it is clear from the observation that the weights and bias matches with the relation defined by us.

# Predicting with our model(Outputs)

In [24]:
training_data['targets'].round(1)

array([[ 16.3],
       [ -5.5],
       [  4.3],
       [ -1.8],
       [ -5.3],
       [  4.5],
       [-24.7],
       [-33.2],
       [ 25.9],
       [ 21.5],
       [ -0.2],
       [ -0.8],
       [ 15.1],
       [  9. ],
       [ -2.6],
       [-33.8],
       [-11.8],
       [-26.1],
       [-19.2],
       [ 12.4],
       [ -4.4],
       [-39.5],
       [  5.9],
       [  9.8],
       [-23.5],
       [-35.4],
       [-33.6],
       [-27.6],
       [-33.9],
       [-14.5],
       [  8.8],
       [ 33.5],
       [-13.4],
       [ 37.6],
       [ 19.2],
       [  3.6],
       [-22.4],
       [-12.9],
       [ 25. ],
       [ 26.9],
       [-10.2],
       [-14.8],
       [-11.5],
       [ -9.6],
       [  4. ],
       [ -2.3],
       [-40.9],
       [-11. ],
       [  3.6],
       [-15.3],
       [ -2.4],
       [ 11.1],
       [-21.2],
       [  5. ],
       [-30.7],
       [ -8.1],
       [ 15.5],
       [ 28. ],
       [-10.9],
       [ -2.1],
       [  3.8],
       [-38.6],
       [

In [27]:
x=model.predict_on_batch(training_data['inputs'])
arr=np.array(x)
arr.round(1)

array([[ 16.9],
       [ -4.9],
       [  4.8],
       [ -2.2],
       [ -4.4],
       [  3.8],
       [-24.7],
       [-33.5],
       [ 25.9],
       [ 20.9],
       [ -1.1],
       [ -1.1],
       [ 15.2],
       [  8.1],
       [ -2.8],
       [-33.2],
       [-11. ],
       [-25.7],
       [-19.7],
       [ 13.1],
       [ -3.6],
       [-39.5],
       [  6.3],
       [  9. ],
       [-23. ],
       [-36.2],
       [-33.9],
       [-28.4],
       [-34.4],
       [-15.5],
       [  9.8],
       [ 33.7],
       [-14.4],
       [ 38. ],
       [ 19.2],
       [  3. ],
       [-21.9],
       [-14. ],
       [ 24.1],
       [ 27.3],
       [-11. ],
       [-15.8],
       [-11.2],
       [-10.4],
       [  4.6],
       [ -1.5],
       [-40.5],
       [-11.9],
       [  3.4],
       [-15.1],
       [ -2.3],
       [ 11.9],
       [-20.6],
       [  4. ],
       [-30. ],
       [ -8.4],
       [ 15. ],
       [ 28.9],
       [-11.2],
       [ -2.6],
       [  4.7],
       [-39.8],
       [

Now you can plot the graph Outputs Vs Targets and observe a straight line, which suggest that the predictions are very much similar to expected outputs.

PS: I'm not plotting the graph, beacuse my Tensorflow 2 environment needs to be re created  in order to support matplot lib.
So please grant me for not providing the graph.